import { Circle, TriangleAlert } from "lucide-react";

interface TaxConfigurationStepProps {
  onBack: () => void;
  onNext: () => void;
}

function TaxOption({
  title,
  subtitle,
  active,
  recommended,
}: {
  title: string;
  subtitle: string;
  active?: boolean;
  recommended?: boolean;
}) {
  return (
    <button
      type="button"
      className={`w-full rounded-[8px] border p-3 text-left ${
        active ? "border-[#5cc7eb] bg-[#f2f8ff]" : "border-slate-200 bg-[#f8fafc]"
      }`}
    >
      <div className="flex items-center justify-between gap-3">
        <div className="text-[15px] font-bold text-slate-800">{title}</div>
        {recommended && (
          <span className="text-[9px] uppercase tracking-[0.16em] px-2 py-0.5 rounded-full bg-[#bdefff] text-[#0c607b] font-bold">
            Recommended
          </span>
        )}
      </div>
      <div className="text-[11px] mt-1 text-slate-500">{subtitle}</div>
      <div className="mt-2 h-8 rounded bg-[#edf3fc] px-3 flex items-center text-[11px] text-slate-500">
        <Circle size={10} className="mr-2 text-slate-400" />
        Example: If price is $10, GST is $1.00.
      </div>
    </button>
  );
}

export function TaxConfigurationStep({ onBack, onNext }: TaxConfigurationStepProps) {
  return (
    <section>
      <h1 className="text-[34px] sm:text-[52px] font-extrabold text-[#0b1324] leading-[1.05] tracking-[-0.02em]">
        Configure your Tax settings
      </h1>
      <p className="text-slate-600 mt-3 text-[15px]">
        Choose how GST is applied to your prices. This affects bills generated by the system.
      </p>

      <div className="mt-8 rounded-[10px] border border-slate-200 bg-white p-5 sm:p-8">
        <div className="grid lg:grid-cols-[1fr_220px] gap-6">
          <div>
            <div className="space-y-3">
              <TaxOption
                title="GST included in price"
                subtitle="The price you enter already includes GST (e.g. Australian Standard)."
                active
                recommended
              />
              <TaxOption
                title="GST added on top"
                subtitle="GST is added on top of your set price at checkout."
              />
              <TaxOption
                title="No tax"
                subtitle="No GST is applied. Used for tax-exempt entities."
              />
            </div>

            <div className="mt-6 max-w-[250px]">
              <label className="text-[12px] font-semibold text-[#111827]">Tax Rate (%)</label>
              <div className="mt-2 h-10 rounded-md bg-[#f1f5fb] px-4 flex items-center justify-between text-[14px] text-slate-700">
                <span>10</span>
                <span>%</span>
              </div>
              <p className="text-[10px] mt-2 text-slate-500">Standard Australian GST is 10%</p>
            </div>

            <div className="mt-5 rounded-[8px] border border-[#f6de9e] bg-[#fff7df] p-3 max-w-[420px]">
              <div className="flex items-start gap-2">
                <TriangleAlert size={15} className="text-[#d98700] mt-0.5" />
                <div>
                  <div className="text-[11px] font-bold text-[#8a5e00]">Important: Finalize carefully</div>
                  <div className="text-[10px] text-[#ad7a0d] mt-0.5">
                    These settings affect every bill. Only admins can change this later.
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="rounded-[14px] bg-[#020819] text-white p-4 shadow-2xl shadow-black/40 max-w-[220px] w-full mx-auto h-[360px]">
            <div className="text-[9px] uppercase tracking-[0.15em] text-slate-400">Receipt Preview</div>
            <div className="mt-7 text-[11px] text-slate-300">Signature Coffee</div>
            <div className="mt-2 h-px bg-white/10" />
            <div className="mt-4 flex justify-between text-[10px] text-slate-300">
              <span>Subtotal</span>
              <span>$9.09</span>
            </div>
            <div className="mt-2 flex justify-between text-[10px] text-slate-300">
              <span>GST 10%</span>
              <span>$0.91</span>
            </div>
            <div className="mt-4 h-px bg-white/10" />
            <div className="mt-4 flex justify-between text-[12px] font-semibold">
              <span>Total Paid</span>
              <span className="text-[#30b7ff]">$10.00</span>
            </div>
          </div>
        </div>

        <div className="mt-8 flex items-center justify-end gap-8">
          <button type="button" onClick={onBack} className="text-[13px] font-medium text-slate-600">
            Back
          </button>
          <button
            type="button"
            onClick={onNext}
            className="h-11 px-8 rounded-full bg-[#07142a] text-white text-[13px] font-semibold shadow-xl shadow-black/20"
          >
            Next →
          </button>
        </div>
      </div>
    </section>
  );
}
